### PR TITLE
Add substitutions

### LINKED ISSUE #9: FR: Add support for pattern substitutions
I'm seeing things like [this](https://github.com/gradio-app/gradio/blob/v3.2/setup.py#L11-L13) frequently:

```python
# Replace relative paths to images with absolute paths
long_description = re.sub("website/homepage/", "https://raw.githubusercontent.com/gradio-app/gradio/main/website/homepage/", long_description)
long_description = re.sub(r"demo/([\S]*.gif)", r"https://raw.githubusercontent.com/gradio-app/gradio/main/demo/\g<1>", long_description)
```

maybe:

```toml
[[tool.hatch.metadata.hooks.fancy-pypi-readme.substitutions]]
find = "website/homepage/"
replace = "https://raw.githubusercontent.com/gradio-app/gradio/main/website/homepage/"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.substitutions]]
find = 'demo/([\S]*.gif)'
replace = 'https://raw.githubusercontent.com/gradio-app/gradio/main/demo/\g<1>'
```

### PR DESCRIPTION
**Pull request by hynek**
Does this cover all bases @ofek?

Fixes #9

### CODE REVIEW

**Comment by ofek** [comment]
Perfect!

**Comment by hynek** [comment]
cool, i’ll push a release later today

**Comment by ofek** [comment]
thanks!

**Comment by hynek** [comment]
Took a bit longer, because I took the time to cleanup validation in #12, but 22.5 is on PyPI now.

**Pull request merged**
