### PR TITLE
Remove pip cache workaround in tests

### PR DESCRIPTION
**Pull request by ofek**
I'll add this to docs

### CODE REVIEW

**Comment by hynek** [comment]
Ah is the caching based on paths and the unpredictable temp path nukes it?

**Comment by ofek** [comment]
Yup!

**Comment by hynek** [comment]
Thanks!

**Comment by hynek** [comment]
@ofek JFTR, your approach gets extremely slow once a .tox and .direnv and what not exist. So I've switched it to copying only the necessary files to build the package and it's much faster now: https://github.com/hynek/hatch-fancy-pypi-readme/commit/da5a577e26506c0441ca8629b7007c7523e11624

Thought that might be interesting for you.

**Comment by ofek** [comment]
Ah ty, I did https://github.com/ofek/hatch-mypyc/commit/616595340c9c4038c18b6fd75ef29604888383f1

**Pull request merged**
